// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const missingEnvVars: string[] = [];
if (!SUPABASE_URL) missingEnvVars.push('VITE_SUPABASE_URL');
if (!SUPABASE_PUBLISHABLE_KEY) missingEnvVars.push('VITE_SUPABASE_PUBLISHABLE_KEY');

if (missingEnvVars.length > 0) {
  console.warn(
    `[Supabase] Variables d'environnement manquantes : ${missingEnvVars.join(', ')}. ` +
    'Les fonctionnalités liées à Supabase (signets cloud, notifications) seront désactivées.'
  );
}

export const supabase = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : null;

export function requireSupabase() {
  if (!supabase) {
    throw new Error(
      'Supabase n\'est pas configuré. Vérifiez que les variables VITE_SUPABASE_URL ' +
      'et VITE_SUPABASE_PUBLISHABLE_KEY sont définies.'
    );
  }
  return supabase;
}